@baseUrl = http://localhost:3333

### Health check
GET {{baseUrl}}/

### Cadastrar senha
POST {{baseUrl}}/auth/definir-senha
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "senha": "eusouoadministrador"
}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "matthew@gmail.com",
    "senha": "umasenhabemlonga"
}

# ### Login
# # @name login
# POST {{baseUrl}}/auth/login
# Content-Type: application/json

# {
#     "email": "admin@gmail.com",
#     "senha": "eusouoadministrador"
# }

### Listar NCs
GET {{baseUrl}}/nao-conformidades
Authorization: Bearer {{login.response.body.token}}

### Criar NC
POST {{baseUrl}}/nao-conformidades
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "titulo": "Teste pelo REST Client",
    "descricao": "Verificando o fluxo completo",
    "requisitoViolado": "Procedimento de teste",
    "dataOcorrencia": "2026-09-01",
    "origem": "OPERACAO",
    "setorId": 1
}

### Criar Usuário 
POST {{baseUrl}}/usuarios
Content-Type: application/json
Authorization: BEARER {{login.response.body.token}}

{
  "nome": "Ana Silva",
  "email": "ana.silva@empresa.com",
  "perfil": "QA",
  "setorId": 1
}