export const Acao = {
    GERENCIAR_RASCUNHO: "GERENCIAR_RASCUNHO", // EDITOR, GERENTE
    PUBLICAR: "PUBLICAR", // EDITOR, GERENTE
    CANCELAR: "CANCELAR", // APROVADOR, GERENTE
    CLASSIFICAR: "CLASSIFICAR", // APROVADOR, GERENTE
    SUBMETER: "SUBMETER", // EDITOR, GERENTE
    APROVAR: "APROVAR", // APROVADOR, GERENTE
    CONCLUIR_VERIFICACAO: "CONCLUIR_VERIFICACAO", // APROVADOR, GERENTE
    REABRIR: "REABRIR", // APROVADOR, GERENTE
    GERENCIAR_COLABORADORES: "GERENCIAR_COLABORADORES", // EDITOR, GERENTE
    DEFINIR_APROVADOR: "DEFINIR_APROVADOR", // APROVADOR, GERENTE
    GERENCIAR_USUARIOS: "GERENCIAR_USUARIOS", // ADMIN
    COMENTAR: "COMENTAR", // EDITOR, APROVADOR, GERENTE
    GERAR_RELATORIOS: "GERAR_RELATORIOS", // GERENTE
    VISUALIZAR: "VISUALIZAR" // VISUALIZADOR, EDITOR, APROVADOR, GERENTE

} as const;

export type Acao = typeof Acao[keyof typeof Acao];